prevnext.settings:
  type: config_object
  label: 'PrevNext settings'
  mapping:
    prevnext_enabled_entity_types:
      type: sequence
      label: 'Enabled Entity Types'
      sequence:
        type: string
    prevnext_enabled_entity_bundles:
      type: sequence
      sequence:
        type: sequence
        label: 'Entity Type'
        sequence:
          type: string
          label: 'Entity Bundle'
