services:
  # Servicio 0: Base de datos MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secure_root_password}
      MYSQL_DATABASE: ${DB_NAME:-idt_drupal}
      MYSQL_USER: ${DB_USER:-idt_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secure_password}
      TZ: America/Bogota
    ports:
      - "33069:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./mariadb/logs:/var/log/mysql
    networks:
      - red_idt_gov_co
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Servicio 1: Proxy Traefik
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=1000"
      - "--providers.file.filename=/dynamic_conf.yml"
    labels:
      - "traefik.enable=true"
      # Dashboard de Traefik
      - "traefik.http.routers.dashboard.rule=Host(`traefik.idt.gov.co`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik@docker"
      - "traefik.http.middlewares.authtraefik.basicauth.users=adminidt:$$apr1$$voIJlj2p$$lBMZgjBqG3IfRlNGCTNpW1"

      # Redirección de idt.gov.co a www.idt.gov.co
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://idt\\.gov\\.co/(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.idt.gov.co/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

      # Router para idt.gov.co que aplica la redirección
      - "traefik.http.routers.redirect-root.rule=Host(`idt.gov.co`)"
      - "traefik.http.routers.redirect-root.middlewares=redirect-to-www"
      - "traefik.http.routers.redirect-root.entrypoints=websecure"
      - "traefik.http.routers.redirect-root.tls=true"
      - "traefik.http.routers.redirect-root.service=idt_nuevo"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/logs:/logs
      - ./traefik/dynamic_conf.yml:/dynamic_conf.yml:ro
      - ./traefik/certs:/certs:ro
    networks:
      - red_idt_gov_co

  # Servicio 2: Nuevo sitio IDT (Drupal 10)
  idt_nuevo:
    build:
      context: .
      dockerfile: .dockerfiles/dockerfile-drupal10
    container_name: idt_nuevo
    restart: unless-stopped
    environment:
      - DRUPAL_DB_HOST=mariadb
      - DRUPAL_DB_NAME=${DB_NAME:-idt_drupal}
      - DRUPAL_DB_USER=${DB_USER:-idt_user}
      - DRUPAL_DB_PASSWORD=${DB_PASSWORD:-secure_password}
      - DRUPAL_BASE_URL=https://www.idt.gov.co
      - TZ=America/Bogota
      - PHP_VERSION=83
    volumes:
      # Código de aplicación (externo - stateless)
      - ./idt_nuevo/drupal:/var/www/html:rw

      # Configuraciones (solo lectura)
      - ./idt_nuevo/config/php/php83-optimized.ini:/usr/local/lsws/lsphp83/etc/php/83/litespeed/php.ini:ro
      - ./idt_nuevo/config/litespeed/httpd_config.conf:/usr/local/lsws/conf/httpd_config.conf:ro
      - ./idt_nuevo/config/litespeed/vhosts_drupal10.conf:/usr/local/lsws/conf/vhosts/drupal10/vhconf.conf:ro

      # Logs (para monitoreo)
      - ./idt_nuevo/logs/php:/var/log/php:rw
      - ./idt_nuevo/logs/litespeed:/usr/local/lsws/logs:rw
    networks:
      - red_idt_gov_co
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idt_nuevo.rule=Host(`www.idt.gov.co`)"
      - "traefik.http.routers.idt_nuevo.entrypoints=websecure"
      - "traefik.http.routers.idt_nuevo.tls=true"
      - "traefik.http.services.idt_nuevo.loadbalancer.server.port=80"
      - "traefik.http.routers.idt_nuevo.middlewares=secure-headers@docker"
      - "traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started

  # Servicio 3: Sitio anterior IDT (Drupal 8)
  idt_anterior:
    build:
      context: .
      dockerfile: .dockerfiles/dockerfile-drupal8
    container_name: idt_anterior
    restart: unless-stopped
    environment:
      - DRUPAL_DB_HOST=mariadb
      - DRUPAL_DB_NAME=${DB_NAME_OLD:-idt_drupal_old}
      - DRUPAL_DB_USER=${DB_USER:-idt_user}
      - DRUPAL_DB_PASSWORD=${DB_PASSWORD:-secure_password}
      - DRUPAL_BASE_URL=https://anterior.idt.gov.co
    volumes:
      - ./antiguo_sitio_web:/var/www/html
      - ./config/php/php74.ini:/usr/local/lsws/lsphp74/etc/php/74/litespeed/php.ini:ro
      - ./config/litespeed/drupal8:/usr/local/lsws/conf/vhosts/drupal8:ro
    networks:
      - red_idt_gov_co
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idt_anterior.rule=Host(`anterior.idt.gov.co`)"
      - "traefik.http.routers.idt_anterior.entrypoints=websecure"
      - "traefik.http.routers.idt_anterior.tls=true"
      - "traefik.http.services.idt_anterior.loadbalancer.server.port=80"
      - "traefik.http.routers.idt_anterior.middlewares=secure-headers@docker"
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started

# Definición de volúmenes
volumes:
  mariadb_data:
    driver: local

# Definición de redes
networks:
  red_idt_gov_co:
    name: red_idt_gov_co
    driver: bridge