#https://hub.docker.com/r/litespeedtech/openlitespeed-drush/tags?name=php83
FROM --platform=linux/amd64 litespeedtech/openlitespeed-drush:1.8.2-lsphp83

ENV PHP_VERSION=lsphp83

# Instalar dependencias PHP disponibles
RUN apt-get update && apt-get install -y \
    ${PHP_VERSION}-common \
    ${PHP_VERSION}-imap \
    ${PHP_VERSION}-pspell \
    ${PHP_VERSION}-tidy \
    ${PHP_VERSION}-pgsql \
    ${PHP_VERSION}-memcached \
    ${PHP_VERSION}-sqlite3 \
    ${PHP_VERSION}-igbinary \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# Instalar Composer y Drush Compabilidad: https://www.drush.org/11.x/install/
RUN curl -sS https://getcomposer.org/installer | /usr/local/lsws/${PHP_VERSION}/bin/php -- --install-dir=/usr/local/bin --filename=composer
RUN /usr/local/lsws/${PHP_VERSION}/bin/php /usr/local/bin/composer global require drush/drush:^12 --with-all-dependencies \
    && ln -s /root/.composer/vendor/bin/drush /usr/local/bin/drush